#######################################################################
# Shift Service - CONFIGURATION                                      #
#######################################################################

# ---------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------
# General application configuration
app:
  mode: "dev"
  port: "9097"
  version: "1.0.0"
  name: "shift-scheduler-service"

# ---------------------------------------------------------------------
# JWT
# ---------------------------------------------------------------------
# JWT token for authentication
auth:
  jwt_pub: |
    superlongtext
    superlongtext
    superlongtext

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Supported Database Engines:
# - postgres = PostgreSQL 9.5 or later
db:
  url: "postgres://postgres:postgres@localhost:5432/shiftdb"

# ---------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------
cache:
  url: "redis://default:1020304050@localhost:6379/0"

# ---------------------------------------------------------------------
# Kafka Broker
# ---------------------------------------------------------------------
broker:
  url: "kafka://:@localhost:9092/file-uploaded-topic"
  consumer_group: "cg-fileuploader"
  topic: "file-uploaded-topic"

# ---------------------------------------------------------------------
# Logger
# ---------------------------------------------------------------------
logger:
  development: true
  disable_caller: false
  disable_stacktrace: false
  encoding: json
  level: info

# ---------------------------------------------------------------------
# Cookies
# ---------------------------------------------------------------------
cookie:
  name: "jwt-token"
  max_age: 86400
  secure: false
  http_only: true

# ---------------------------------------------------------------------
# Session
# ---------------------------------------------------------------------
session:
  name: "session-id"
  prefix: "api-session"
  expire: 3600

# ---------------------------------------------------------------------
# Metrics (Prometheus)
# ---------------------------------------------------------------------
metrics:
  url: "0.0.0.0:7070"
  service: "api"

# ---------------------------------------------------------------------
# Tracing (Jaeger)
# ---------------------------------------------------------------------
jaeger:
  host: "localhost:6831"
  service_name: "REST_API"
  log_spans: false

# ---------------------------------------------------------------------
# AWS S3
# ---------------------------------------------------------------------
cdn:
  endpoint: ""
  region: ""
  bucket: ""
  access_key: ""
  secret_key: ""