basePath: /shift-scheduler-service
definitions:
  handlers.RespondJson:
    properties:
      intent:
        type: string
      message: {}
      status:
        type: boolean
    type: object
  handlers.updateShiftScheduleDTO:
    properties:
      alias:
        type: string
      description:
        type: string
      end_date:
        type: string
      frequency:
        description: 1, 2, 3, 4, 5, 6, 7 (days of the week)
        type: integer
      manager:
        items: {}
        type: array
      organization:
        items: {}
        type: array
      shifts:
        items: {}
        type: array
      start_date:
        type: string
      status:
        description: '0: pending, 1: approved, 2: rejected'
        type: integer
      users:
        items: {}
        type: array
      year:
        type: integer
    required:
    - alias
    - description
    - end_date
    - frequency
    - manager
    - organization
    - shifts
    - start_date
    - users
    - year
    type: object
info:
  contact:
    email: YunusAlpu@icloud.com
    name: Yunus Emre Alpu
    url: https://yunusemrealpu.netlify.app
  title: Shift Scheduler Service API
  version: 1.0.0
paths:
  /shift-schedule/{id}:
    put:
      consumes:
      - application/json
      description: update a shift schedule
      parameters:
      - description: Shift Schedule ID
        in: path
        name: id
        required: true
        type: string
      - description: update shift schedule
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.updateShiftScheduleDTO'
      produces:
      - application/json
      responses:
        "200":
          description: successfully updated shift schedule
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot update shift schedule due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot update shift schedule due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot update shift schedule due to internal server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: update a shift schedule
      tags:
      - Shift
  /shift-schedules:
    get:
      consumes:
      - application/json
      description: get all shift schedules
      produces:
      - application/json
      responses:
        "200":
          description: get all shift schedules successfully
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot get all shift schedules due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot get all shift schedules due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot get all shift schedules due to internal server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: get all shift schedules
      tags:
      - Shift
    post:
      consumes:
      - application/json
      description: create a new shift schedule
      parameters:
      - description: Alias
        in: body
        name: alias
        required: true
        schema:
          type: string
      - description: Description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: Frequency
        in: body
        name: frequency
        required: true
        schema:
          type: integer
      - description: Start Date
        in: body
        name: start_date
        required: true
        schema:
          type: string
      - description: End Date
        in: body
        name: end_date
        required: true
        schema:
          type: string
      - description: Year
        in: body
        name: year
        required: true
        schema:
          type: integer
      - description: Status
        in: body
        name: status
        required: true
        schema:
          type: integer
      - description: Organization
        in: body
        name: organization
        required: true
        schema:
          type: object
      - description: Manager
        in: body
        name: manager
        required: true
        schema:
          type: object
      - description: Users
        in: body
        name: users
        required: true
        schema:
          type: object
      - description: Shifts
        in: body
        name: shifts
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: successfully created shift schedule
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot create shift schedule due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot create shift schedule due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot create shift schedule due to internal server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: create a new shift schedule
      tags:
      - Shift
  /shift-schedules/{id}:
    delete:
      consumes:
      - application/json
      description: delete a shift schedule
      parameters:
      - description: Shift Schedule ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successfully deleted shift schedule
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot delete shift schedule due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot delete shift schedule due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot delete shift schedule due to internal server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: delete a shift schedule
      tags:
      - Shift
  /shift-schedules/{id}/restore:
    patch:
      consumes:
      - application/json
      description: restored a shift schedule
      parameters:
      - description: Shift Schedule ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: successfully restored shift schedule
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot restore shift schedule due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot restore shift schedule due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot restore shift schedule due to internal server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: restore a shift schedule
      tags:
      - Shift
  /shift-schedules/{year}:
    get:
      consumes:
      - application/json
      description: get a shift schedules by year
      parameters:
      - description: Shift Schedule Year
        in: path
        name: year
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: get shifts by year successfully
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot get shifts schedule by year due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot get shifts schedule by year due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot get shifts schedule by year due to internal server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: get a shift schedules by year
      tags:
      - Shift
  /shift-schedules/deleted:
    get:
      consumes:
      - application/json
      description: get all deleted shift schedules
      parameters:
      - description: Shift Schedule ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: get all shift schedules successfully
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot get only deleted shift schedules due to invalid request
            body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot get only deleted shift schedules due to invalid request
            body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot get only deleted shift schedules due to internal server
            error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: get all deleted shift schedules
      tags:
      - Shift
  /shift-schedules/id:
    get:
      consumes:
      - application/json
      description: get a shift schedule by id
      parameters:
      - description: Shift Schedule ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: get shift by id successfully
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot get shift schedule by id due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot get shift schedule by id due to invalid request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot get shift schedule by id due to internal server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: get a shift schedule by id
      tags:
      - Shift
  /shift-schedules/paginated:
    get:
      consumes:
      - application/json
      description: get all shift schedules with pagination
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      - description: orderBy
        in: query
        name: orderBy
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: get all shift schedules successfully
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot get shift schedules  with pagination due to invalid
            request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot get shift schedules  with pagination due to invalid
            request body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot get shift schedules  with pagination due to internal
            server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: get all shift schedules with pagination
      tags:
      - Shift
  /shift-schedules/week:
    get:
      consumes:
      - application/json
      description: get shift schedules by current week
      produces:
      - application/json
      responses:
        "200":
          description: get shifts by current week successfully
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot get shifts schedule by current week due to invalid request
            body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot get shifts schedule by current week due to invalid request
            body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot get shifts schedule by current week due to internal
            server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: get shift schedules by current week
      tags:
      - Shift
  /shift-schedules/week/paginated:
    get:
      consumes:
      - application/json
      description: get shift schedules by week with pagination
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      - description: orderBy
        enum:
        - asc
        - desc
        in: query
        name: orderBy
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: get shifts by current week successfully
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "400":
          description: cannot get shifts schedule by current week due to invalid request
            body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "422":
          description: cannot get shifts schedule by current week due to invalid request
            body
          schema:
            $ref: '#/definitions/handlers.RespondJson'
        "500":
          description: cannot get shifts schedule by current week due to internal
            server error
          schema:
            $ref: '#/definitions/handlers.RespondJson'
      security:
      - BearerAuth: []
      summary: get shift schedules by current week with pagination
      tags:
      - Shift
schemes:
- http
- https
swagger: "2.0"
